import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import TransitionProvider from "@/components/transitionProvider";

const jetbrains_mono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "solarluiso portfolio app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrains_mono.className}>
        <TransitionProvider>{children}</TransitionProvider>
      </body>
    </html>
  );
}
